### ISSUE TITLE
Doc and CLI different for moving file into subdirectory

### ISSUE THREAD

**Issue by bjkeller** [SD2E/api-user-guide#8]
There is a difference b/w  cli-api and the documentation for moving a file into a subdirectory.

I uploaded a file to my default file system, made a directory and then attempted to move the file into the directory based on the example from
https://sd2e.github.io/api-user-guide/docs/data_management.html#other-file-operations
But get an error:

% files-move -D q0-yeast-gates yeast-gates-labels.csv
Folder at q0-yeast-gates already exists

This works 

% files-move -D q0-yeast-gates/yeast-gates-labels.csv yeast-gates-labels.csv

**Comment by wjallen** [comment]
Thank you for pointing this out! It has been fixed.
